[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "IntrinsicTime"
version = "0.1.0"
authors = [{ name = "Tom Houweling", email = "thomas.houweling@gmail.com" }]
description = "Utilities for intrinsic time decomposition and fractal event analysis"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"
dependencies = ["numpy", "pandas", "scipy", "plotly"]

[tool.setuptools.packages.find]
where = ["IntrinsicTime"]
